#!/usr/bin/env bash

go build 'github.com/akramarenkov/esam/src/esamd'
go build 'github.com/akramarenkov/esam/src/esamc'

# Agent can be built without libc dependency
# See https://golang.org/pkg/os/user/ for none-cgo specificities
# export CGO_ENABLED=0
go build 'github.com/akramarenkov/esam/src/esama'
